### ISSUE TITLE
No files or workbooks found

### ISSUE THREAD

**Issue by joshtemple** [Squarespace/datasheets#6]
I've set up a Google service account for a Google Drive folder and I'm able to instantiate the datasheets client using `service=True`. However, running `fetch_workbooks_info` and `fetch_folders` both return empty dataframes.

```
import datasheets
client = datasheets.Client(service=True)
client.fetch_workbooks_info()
```

Using Google's Drive API Explorer (linked from my datasheets Google project Dashboard), I'm able to see plenty of files in this Drive, so it shouldn't be an issue with the Drive. Somehow, datasheets isn't finding those files.

**Comment by zcmarine** [comment]
Hey Josh,

Did you share the workbooks with that service account? Service accounts don't use your personal OAuth credentials, so you won't see things shared with you as a person: the service accounts are separate accounts and need to be given access.

**Comment by joshtemple** [comment]
That fixed it! I used the ID under Service account ID in the Google Cloud Console, found under Credentials >> Manage service accounts. I shared my workbook with that ID in Google Drive and then it appeared in datasheets. Was that the correct sequence to follow?

**Comment by zcmarine** [comment]
Yup, that'll do it! If you don't want to keep navigating the confusing Google Cloud Console, you could also get the email address you want like so:

```
>>> import datasheets as ds
>>> client = ds.Client(service=True)
>>> client.email
my-service@datasheets-example.iam.gserviceaccount.com
```

I find that simpler, but they both get you the same email so either works. :)

Since it sounds like this resolved your problem, is it ok if I close this issue?

**Comment by joshtemple** [comment]
Very helpful, thanks! Please go ahead and close.
